"""add_payment_distribution_transaction_junction_tables

Revision ID: 39e953a631c3
Revises: badb62cb666c
Create Date: 2026-01-29 22:47:53.757803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39e953a631c3'
down_revision = 'badb62cb666c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create junction table for payment-transaction many-to-many
    op.create_table('payment_transactions',
        sa.Column('payment_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('payment_id', 'transaction_id')
    )
    
    # Create junction table for distribution-transaction many-to-many
    op.create_table('distribution_transactions',
        sa.Column('distribution_id', sa.String(), nullable=False),
        sa.Column('transaction_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('distribution_id', 'transaction_id')
    )
    
    # Column alterations detected by autogenerate (schema sync)
    op.alter_column('payments', 'obligation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'debit'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop junction tables
    op.drop_table('distribution_transactions')
    op.drop_table('payment_transactions')
    
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'debit'::character varying"))
    op.alter_column('payments', 'payment_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payments', 'obligation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###

