"""Add payroll_transfers table

Revision ID: 6f5a27f6a6ff
Revises: dc645b448d3d
Create Date: 2026-01-29 00:33:13.963042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f5a27f6a6ff'
down_revision = 'dc645b448d3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create payroll_transfers table
    op.create_table('payroll_transfers',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('source_account_id', sa.String(), nullable=False),
        sa.Column('target_account_id', sa.String(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('billing_month', sa.String(), nullable=False),
        sa.Column('note', sa.String(), nullable=True),
        sa.Column('transaction_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ),
        sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.alter_column('payments', 'obligation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'debit'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'debit'::character varying"))
    op.alter_column('payments', 'payment_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payments', 'obligation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('payroll_transfers')
    # ### end Alembic commands ###
