"""Add balance_after_transaction

Revision ID: 9880b1b7852e
Revises: 
Create Date: 2026-01-16 16:47:06.333182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9880b1b7852e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligations', 'archived')
    
    # 1. Drop the default constraint first to avoid casting errors on the default value
    op.alter_column('payments', 'status', server_default=None)

    # 2. explicitly create the enum type if it doesn't exist (handled by sa.Enum usually, but let's be safe via the alter_column implicit creation)
    # Note: sa.Enum(...) inside alter_column usually emits CREATE TYPE if needed.
    # We use postgresql_using to handle the data conversion.
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PAID', 'PENDING', name='paymentstatus'),
               existing_nullable=True,
               postgresql_using="status::paymentstatus")
               
    # 3. Re-apply the default with the correct ENUM casting
    op.alter_column('payments', 'status', server_default=sa.text("'PAID'::paymentstatus"))

    op.drop_index(op.f('ix_obligation_history_id'), table_name='payments')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.add_column('transactions', sa.Column('balance_after_transaction', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'balance_after_transaction')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index(op.f('ix_obligation_history_id'), 'payments', ['id'], unique=False)
    
    # Downgrade logic: Drop default, convert back to VARCHAR, re-add String default
    op.alter_column('payments', 'status', server_default=None)
    
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PAID', 'PENDING', name='paymentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="status::varchar") # Explicit cast back
               
    op.alter_column('payments', 'status', server_default=sa.text("'PAID'::character varying"))
    
    # Optional: Drop the type if we want to be clean, but usually Alembic leaves types? 
    # op.execute("DROP TYPE paymentstatus") 

    op.add_column('obligations', sa.Column('archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
