"""Add balance_after_transaction

Revision ID: 9880b1b7852e
Revises: 
Create Date: 2026-01-16 16:47:06.333182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9880b1b7852e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligations', 'archived')
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PAID', 'PENDING', name='paymentstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'PAID'::character varying"),
               postgresql_using="status::paymentstatus")
    op.drop_index(op.f('ix_obligation_history_id'), table_name='payments')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.add_column('transactions', sa.Column('balance_after_transaction', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'balance_after_transaction')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index(op.f('ix_obligation_history_id'), 'payments', ['id'], unique=False)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PAID', 'PENDING', name='paymentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'PAID'::character varying"))
    op.add_column('obligations', sa.Column('archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
